  services:
    sql-server:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: Steiner_Bibliothek_WPF
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Passwort123! # Wichtig: Merk dir das!
      ports:
        - "1433:1433"
