// <auto-generated />
using System;
using Bibliothek;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliothek.Migrations
{
    [DbContext(typeof(BibliothekContext))]
    [Migration("20260218140653_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bibliothek.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuchId")
                        .HasColumnType("int");

                    b.Property<int>("Jahrgang")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuchId");

                    b.ToTable("Autoren");
                });

            modelBuilder.Entity("Bibliothek.Buch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnzahlSeiten")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerlagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerlagId");

                    b.ToTable("Buecher");
                });

            modelBuilder.Entity("Bibliothek.Ort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orte");
                });

            modelBuilder.Entity("Bibliothek.Verlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmensitzId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirmensitzId");

                    b.ToTable("Verlage");
                });

            modelBuilder.Entity("Bibliothek.Autor", b =>
                {
                    b.HasOne("Bibliothek.Buch", null)
                        .WithMany("Autoren")
                        .HasForeignKey("BuchId");
                });

            modelBuilder.Entity("Bibliothek.Buch", b =>
                {
                    b.HasOne("Bibliothek.Verlag", "Verlag")
                        .WithMany()
                        .HasForeignKey("VerlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verlag");
                });

            modelBuilder.Entity("Bibliothek.Verlag", b =>
                {
                    b.HasOne("Bibliothek.Ort", "Firmensitz")
                        .WithMany()
                        .HasForeignKey("FirmensitzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firmensitz");
                });

            modelBuilder.Entity("Bibliothek.Buch", b =>
                {
                    b.Navigation("Autoren");
                });
#pragma warning restore 612, 618
        }
    }
}
