// <auto-generated />
using System;
using Bibliothek;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliothek.Migrations
{
    [DbContext(typeof(BibliothekContext))]
    [Migration("20260303104529_NullableBeziehungen")]
    partial class NullableBeziehungen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bibliothek.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Jahrgang")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autoren");
                });

            modelBuilder.Entity("Bibliothek.Buch", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnzahlSeiten")
                        .HasColumnType("int");

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerlagId")
                        .HasColumnType("int");

                    b.HasKey("ISBN");

                    b.HasIndex("AutorId");

                    b.HasIndex("VerlagId");

                    b.ToTable("Buecher");
                });

            modelBuilder.Entity("Bibliothek.Ort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Postleitzahl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orte");
                });

            modelBuilder.Entity("Bibliothek.Verlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirmensitzId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirmensitzId");

                    b.ToTable("Verlage");
                });

            modelBuilder.Entity("Bibliothek.Buch", b =>
                {
                    b.HasOne("Bibliothek.Autor", "Autor")
                        .WithMany("Buecher")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bibliothek.Verlag", "Verlag")
                        .WithMany()
                        .HasForeignKey("VerlagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");

                    b.Navigation("Verlag");
                });

            modelBuilder.Entity("Bibliothek.Verlag", b =>
                {
                    b.HasOne("Bibliothek.Ort", "Firmensitz")
                        .WithMany("Verlage")
                        .HasForeignKey("FirmensitzId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Firmensitz");
                });

            modelBuilder.Entity("Bibliothek.Autor", b =>
                {
                    b.Navigation("Buecher");
                });

            modelBuilder.Entity("Bibliothek.Ort", b =>
                {
                    b.Navigation("Verlage");
                });
#pragma warning restore 612, 618
        }
    }
}
